### ISSUE TITLE
Chrome toolbar icon progress bar stuck indefinitely at 100%

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#1003]
In Chrome, the toolbar icon does not hide the green progress bar after running internal DB updates, it's just sitting indefinitely at 100%:

![toolbar screenshot](https://user-images.githubusercontent.com/28300/196424546-f01fb14c-a0ce-4731-91a3-4b3e90034741.png)

Only after clicking on the icon (disable/enable), the progress bar disappears:

![image](https://user-images.githubusercontent.com/28300/196424925-dc819b77-dac8-4f8a-922d-a95f9db8786e.png)

**Comment by birtles** [comment]
Yes, I've definitely seen this on Edge before. I tried to debug it last week but couldn't reproduce it.

If it happens again, would you be able to hover over the icon and tell me what it says?

I'm trying to determine if it's a problem with the final update not occurring or if it's a race condition involving loading the icons. I suspect it's the latter.

**Comment by Tomalak** [comment]
It does not say anything special.

![image](https://user-images.githubusercontent.com/28300/197374207-86b1a0ea-0d0a-4dd6-8657-36e9e256a009.png)

**Comment by birtles** [comment]
Thanks that's very helpful.

I think that eliminates the possibility that the final database update is not being received. Instead, my guess is that in Chromium-based browsers, `setIcon` are not guaranteed to be FIFO. That is, my current theory is we have the following situation:

1. We get a database update saying "100%"
2. We call `setIcon` asynchronously to load and set the 100% icon
3. While `setIcon` is still running we get another database update saying "All done"
4. We call `setIcon` asynchronously to load and the set done icon
5. Because the done icon has already been used (it's the default icon) it loads from the cache and is displayed
6. The first call to `setIcon` finally completes and overrides the second call, displaying the 100% icon
