### ISSUE TITLE
Better cross-referencing of rendaku suffixes

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#1090]
This is just an idea, not sure if it is feasible.

Would it be possible to cross-reference words that start with dakuten kana (i.e. rendaku) to their "plain" entries? For example

借り**ぐらし**　->　**くらし** 

![ぐらし does not resolve to くらし](https://user-images.githubusercontent.com/28300/221152493-7c71781c-4c96-4be3-82b9-e5096a2d9734.png)

![but くらし exists](https://user-images.githubusercontent.com/28300/221152603-33f688b7-a535-4e39-92a6-6c8b13a3bc26.png)

**Comment by birtles** [comment]
I took a shot at doing this. For the example here it gives the following result:

![image](https://user-images.githubusercontent.com/1232595/222135609-d6d92c6a-e2ce-45f0-a5cd-bfef230e7d99.png)

It currently will only show a match if the entry has a gloss marked as being a suffix so it might not show as often as it should but it's probably best to be conservative rather than showing wrong results but being too zealous about dropping dakuten.

**Comment by birtles** [comment]
I've been looking for examples of this and I don't find too many. Common ones already appear in the dictionary with rendaku (e.g. ぐらい) and even after restricting the results to suffixes, there's still a good chance of false positives (e.g. じだい being recognized as 次第 even though 次第 is almost always しだい).

**Comment by Tomalak** [comment]
Yeah, that sounds like the predicament that made me say "not sure if it's feasible" in the beginning. Oh well.

But thanks for giving it a shot!

**Comment by birtles** [comment]
For the specific case of ぐらし I've manually added an entry to the 10ten data export (should be live in an hour or two) and I've proposed a change to JMdict to add a search-only form upstream.

**Comment by Tomalak** [comment]
Thanks for investing all that effort for an edge case. :)
