### ISSUE TITLE
[Feature Request] Clickable kanji to get individual definitions from "words" tab

### ISSUE THREAD

**Issue by scallensc** [birchill/10ten-ja-reader#1138]
Hey there, just wondering if it's possible to add the option for similar functionality as Yomichan, in that you can click on each kanji of a word and get the individual kanji definitions:
https://user-images.githubusercontent.com/9414927/231941891-e0a03b05-beda-4378-a8e6-676a1f514531.mov  
At present, 10ten just takes you to the copy page, and the "kanji" tab only shows the first kanji for a parsed jukugo, so you have to re-engage it for each individual kanji - I often want to check an individual kanji in the middle of a word, so this would be a real timesaver!  
Appreciate users probably have a muscle memory for the current functionality, so perhaps a toggle or hotkey?

**Comment by birtles** [comment]
Hi @scallensc!

Thanks for posting this issue. I'm afraid I couldn't playback the video (I tried in Firefox, Chrome, and Windows Media Player but with no luck).

Some users have commented that the popup window is too big so I'd like to experiment with only showing the first few entries and having the user scroll to see later ones. I think we could extend that to the kanji tab, so that we show all the kanji entries for the longest match and you can scroll down to see them all. Would that work do you think?

**Comment by scallensc** [comment]
Hi @birtles!  

Thanks for the reply. Odd, it's H265 so might be a lack of HEVC codecs, sorry about that, they aren't included in Windows without paying MS $0.99 for a download from the MS store - VLC is a great alternative that should play virtually everything without issue though. 

I don't think you need to bother watching the video, it's just demonstrating how it functions in Yomichan, your suggestion actually sounds better, in Yomichan you click each individual kanji and it takes you to that defintion, but then you have to click a back arrow to go back to the word to click a subsequent kanji, etc. Having all the entries from the longest match in the kanji tab and scrollable would be absolutely awesome!

**Comment by birtles** [comment]
Thanks for the quick feedback. Great! That seems doable and would dovetail nicely into the changes to reduce the height of the popup (which is the major item on the roadmap, after I get the text lookup rewrite landed).

**Comment by birtles** [comment]
Version 1.15 has now been released which includes this feature.
