### ISSUE TITLE
Currency converter is confused by number suffixes (multipliers)

### ISSUE THREAD

**Issue by SaltfishAmi** [birchill/10ten-ja-reader#1399]
An interesting example:

![image](https://github.com/birchill/10ten-ja-reader/assets/14184974/4864fd6f-ed18-4cb0-a724-7a7a1b2a63a1)

(Hovering over 8 does not have any effect)

---

![image](https://github.com/birchill/10ten-ja-reader/assets/14184974/c1e01128-777d-49d0-b74e-bb3d48505988)

I am looking for jobs in Japan (就活), and above two are actual examples of company information (not made up by me!).

Although I do think some of these multipliers look really weird, like, why use western 10^3 based multipliers when you write in Japanese??

余談ですが, in China, we write 1万元 or 1億元, we also write ￥10k or ￥100m, but I never see anyone write 10千元 or 100百万元 ... if a company has only 1,000 CNY of capital, we would write 0.1万元. I don't know the conventions in Japan but this really looks ... hmmm ... westernized.

**Comment by birtles** [comment]
Yeah, those a really odd. I recently fixed a bug so that 39,800万円 is recognized which I encountered here: https://www.athome.co.jp/kodate/1008941087/

I'm not sure if the thinking there is that real estate figures are typically quoted in 万円 so 39,800万円 is more natural to talk about than 3.98億円?

I haven't released a version with that fix yet, however.

However, 123,456,789百万円 seems like a suspicious number for 売上高! I think someone might be cooking the books. Best to steer clear of that company!

I'll see what I can do about the other cases here. For my testing, here they are as text:

- 123,456,789百万円
- 11,786百万円
- 3,307,675千円

I notice that last one already works on the latest trunk build (i.e. will be fixed in the next release).

Good luck with your 就活!
