### ISSUE TITLE
Allow swiping between tabs

### ISSUE THREAD

**Issue by StarScape** [birchill/10ten-ja-reader#1653]
Hi, and first of all, thank you for developing 10ten reader! It has made reading Japanese webpages on iOS actually possible for me. Previously, my only ways to look up words were (a) install the JA->EN dictionary and use iOS's built in "Look Up" feature, which is slow and cumbersome, or (b) copy-paste the word into a dictionary in another tab, which is even more annoying. 10ten is _much_ easier.

Like I said, I use it on mobile, and the feature I'd like to see is the ability to swipe between the tabs in the popup. I frequently want to look at the kanji tab when seeing a new word, and being able to just quickly swipe right and then swipe back would be a bit quicker than tapping.

I think this goes nicely with existing behavior too, since you can already swipe up/down on the kanji tab to go to the prev/next kanji.

![image](https://github.com/birchill/10ten-ja-reader/assets/4681820/c56cc6a7-cc7a-4918-a40f-b5e7a97936c7)

If this is something the maintainer(s) are cool with and willing to merge, I'd like a stab at implementing this myself. I'm trying to get back into open source after a long time and this seems like a good first issue.

**Comment by birtles** [comment]
Hi @StarScape! Thank you very much for your very kind words.

Excellent suggestion regarding swiping to move between the tabs. I'd be very happy to review/merge such a feature.

Two challenges to be aware of, however:

1. Currently the code for the popup (under `src/content/popup/`) is all very redundant manual DOM manipulation. Making the swipe _animated_ could be tricky under the current setup. In the coming months I hope to rewrite the whole popup in Preact making it easier to add dynamic effects but for now it's pretty dumb code to work with.
2. As you probably know, it's possible to tap entries in the popup in order to copy them. As a result, I guess we'll need to differentiate between a click and a swipe. It's possible we can use native drag events and get this distinction for free, but otherwise otherwise we might need to manually add  heuristic to differentiate between the two.

**Comment by StarScape** [comment]
@birtles thanks for the reply and the good info.

I think the easiest thing to do for now will be to implement it without animation. One could always be put in later once the popup gets Preactified. Will keep in mind about making sure the click and swipe gets properly differentiated too.

I’m a little busy the next couple of days with a technical take home (yay being unemployed 🙂!), but I’ll most likely be opening a PR in the next week-ish. I already read the CONTRIBUTING.md, lmk if there’s anything else I should keep in mind.

**Comment by birtles** [comment]
> I’m a little busy the next couple of days with a technical take home (yay being unemployed 🙂!), but I’ll most likely be opening a PR in the next week-ish. I already read the CONTRIBUTING.md, lmk if there’s anything else I should keep in mind.

Thanks! What you have looks great. All the best with the interview!

**Comment by birtles** [comment]
Fixed by #1656

**Comment by StarScape** [comment]
Hey @birtles, resurrecting the discussion here because I recall you said

>  In the coming months I hope to rewrite the whole popup in Preact [...]

and, after poking through the code today, I actually think this would be kinda fun to do. I think I could convert it to Preact a bit at a time too, by temporarily replacing calls to `renderX()` functions (e.g. `renderPopup()`) with a separate call to `ReactDOM.render` (not sure how I'll do the parameter passing in the meantime, but I can figure that out).

How would you feel about me starting on the conversion? Don't want to step on any toes, in case you've already started, or there's a specific way you had in mind of going about it. My plan would be to open a draft PR and work on it there, rather than do it all at once.

**Comment by birtles** [comment]
Hi @StarScape!

> Hey @birtles, resurrecting the discussion here because I recall you said
> 
> > In the coming months I hope to rewrite the whole popup in Preact [...]
> 
> and, after poking through the code today, I actually think this would be kinda fun to do. I think I could convert it to Preact a bit at a time too, by temporarily replacing calls to `renderX()` functions (e.g. `renderPopup()`) with a separate call to `ReactDOM.render` (not sure how I'll do the parameter passing in the meantime, but I can figure that out).
> 
> How would you feel about me starting on the conversion? Don't want to step on any toes, in case you've already started, or there's a specific way you had in mind of going about it. My plan would be to open a draft PR and work on it there, rather than do it all at once.

Absolutely, that would be great. The process I have in mind is to just convert one small part of the kanji window and ship that first, then gradually cover the rest of the kanji tab. In particular I had in mind to start with just the table of references at the bottom of that window.

Also, I hoped to convert the CSS to Tailwind in the process because the current CSS is really hard to maintain.

I'd also like to set up React Cosmos fixtures for these components so we can easily test how they look in different configurations, different themes, different localizations etc. That complicates things a bit because we need to make sure the localization (which currently uses `browser.i18n.getMessage`) can work in non-extension contexts. The good news is we've already done that for the options page so we should be able to use a similar approach here.

So I'd probably approach this with something like the following:

1. Create a `KanjiReferencesTable.tsx` component and `KanjiReferencesTable.fixture.tsx` component in `src/content/popup` and work out how to get our React Cosmos setup to render it.
2. Add a couple of fixture variants to cover even vs odd numbers of rows.
3. Set up some sort of localization helper similar to what we do in the options page and get the various localized strings to render. Like the options page, we should add a fixture decorator (or whatever it's called) that allows you to switch locales while previewing the component.
4. Replace the point where we render the reference table with a call to `React.render`. This will mean we end up pulling Preact into the content bundle so we should check the file size isn't bloated too much by that.

Getting that much to work would be a great start. Then we can tackle the styles as a second patch/PR.

For the options page I approached the styles something like:

1. Set up Tailwind to work with the existing stylesheet (and not import the Tailwind reset styles, I think) 
2. Add a prop to the component to toggle between the existing styles and the Tailwind styles
3. In the fixture, render the component twice: once with the existing styles and once with the tailwind styles
4. In the component, for each `class` attribute etc. toggle between the existing styles and corresponding tailwind styles (including using theme values like `bg-[--cell-highlight-bg]` ([ref](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values))
5. Set up a fixture decorator to allow toggling the theme somehow
6. Iterate until the two versions look the same (or the newer one looks better). We might make some improvements along the way like, for example, using container queries instead of media queries to make the component responsive.
7. Drop the prop and old styles and remove any no longer needed CSS

It's a lot of work, but once we have that it's going to be a lot easier to work with these popup components in future. It will mean we can:

- Easily test the localization
- Easily test the themes
- Easily test different screen/popup sizes
- Easily test all the different permutations of content
- Make the localization controllable via a setting (#701)

If that all sounds too involved I'm happy to set it up in the coming weeks and let you iterate on the individual components.

**Comment by StarScape** [comment]
Hey Brian, thanks for the detailed context as always, it helps a lot. I'm going to further digest what you wrote tomorrow when I'm back at my desk, but what you outlined makes sense and should give me enough to at least get started on this myself. Definitely agree that getting Cosmos and Tailwind working for these parts of the UI would be great.
