### ISSUE TITLE
Add keyboard shortcuts for navigating in popup

### ISSUE THREAD

**Issue by StarScape** [birchill/10ten-ja-reader#1738]
I'm a keyboard-centric user myself, and I frequently flip back and forth between the `Words` and `Kanji` tab. You can already use the up/down arrow keys to navigate between different kanji in the `Kanji` tab, I think it would be nice to be able to use the left/right arrow keys to flip between tabs, basically a desktop-equivalent of #1653.

My only concern is how this might work with focus. Currently you have to focus the kanji tab content area in order for the up/down arrow shortcuts to work. We would probably want the 10ten popup window to be focused in order for the left/right arrow shortcuts to work—but auto-focusing it seems like questionable accessibility practice, not to mention it could be annoying when using the plugin on an editable element.

**Comment by birtles** [comment]
Right, focus is the hard part here. We disable most of the shortcut keys when the user has focussed a text input and we'd need to disable <kbd>←</kbd> and <kbd>→</kbd> for similar reasons.

Two of the existing shortcut keys for toggling tabs—<kbd>Shift</kbd> and <kbd>Ctrl</kbd>—continue to work when focussed in a text area, however, since tapping those keys don't normally have any effect.

We also have <kbd>n</kbd> as an option for toggling tabs but I don't remember when we added that or why.

For <kbd>Shift</kbd> / <kbd>Ctrl</kbd> I suppose we'd break existing users' workflows if we tried to distinguish between left and right Shift/Ctrl such that they cycle in opposite directions?

**Comment by StarScape** [comment]
> Two of the existing shortcut keys for toggling tabs—Shift and Ctrl—continue to work when focussed in a text area, however, since tapping those keys don't normally have any effect.

Oh, I didn't actual realize I could toggle tabs like that 🙂. That already fills the need I was talking about here, so I think I can safely close this.
