### ISSUE TITLE
Additional yen conversion parsing

### ISSUE THREAD

**Issue by 0xNF** [birchill/10ten-ja-reader#2000]
In multilingual discussions on the internet, I often encounter yen-denominated sums written with k, m, or t metric suffixes, for example, 40k円, which doesn't parse in 10ten. 

What do the maintainers think of allowing these suffixes to be parsed?

**Comment by birtles** [comment]
Absolutely. We already parse some pretty non-standard numbers and I'm more than happy to add more if they occur in the wild.

Do you happen to have any URLs with examples of these variants?

**Comment by 0xNF** [comment]
It's most prevalent on reddit:
* [Japan Dentist - from 40k to 200k円](https://old.reddit.com/r/japanlife/comments/1fo8alm/japan_dentist_from_40k_to_200k%E5%86%86/)
* [...at about 1k 円 for 240 blank cards...](https://old.reddit.com/r/japanlife/comments/15o1kci/what_do_you_use_for_physical_flashcards/)

But you'll sometimes see it on explainer sites in Japanese:
* [1K円＝1,000円という表現が生まれたのですね。](https://news.cardmics.com/entry/1k-1m-howmuch/)
* [1,000,000円＝1,000k円＝1M円です](https://oshiete.goo.ne.jp/qa/1304275.html)

To say nothing of the discord chats it sometimes comes up in. It's mostly an English-Japanese speaker thing.

**Comment by birtles** [comment]
Thank you! So basically 洋製日本語. Nice.

**Comment by SaltfishAmi** [comment]
> What is the t suffix used for?

兆円, I guess??

**Comment by 0xNF** [comment]
Trillion yen, often seen in discussions of government fiscal budgets.

**Comment by birtles** [comment]
I've done a basic implementation of this over in #2049 but looking at the [dentist thread](https://old.reddit.com/r/japanlife/comments/1fo8alm/japan_dentist_from_40k_to_200k%E5%86%86/) from [an earlier comment](https://github.com/birchill/10ten-ja-reader/issues/2000#issuecomment-2374484482) I guess it would be more useful if this recognized "5k yen" too?

I'm not sure if it's ever going to recognize the "40k" in "40k to 200k円", however, since that would require parsing quite a bit more of the context to make that work.

**Comment by birtles** [comment]
Updated #2049 to cover "5k yen" too.

**Comment by birtles** [comment]
> This is fantastic, thanks so much.

Thank you!
