### ISSUE TITLE
Not working with fullscreen Netflix

### ISSUE THREAD

**Issue by Orzelius** [birchill/10ten-ja-reader#466]
Like the title says, the popup isn't visible on full screen Netflix. Works with youtube though.

Example: (working when not full screen and when full screen the popup is not displayed)
![sub](https://user-images.githubusercontent.com/33936483/101726195-b7635300-3aba-11eb-8409-884f3baf0f56.gif)

**Comment by SaltfishAmi** [comment]
Possibly a z-index issue?

**Comment by birtles** [comment]
I think the issue here is that the fullscreen API works by taking a specific element and making it occupy the whole screen.

However, the Rikaichamp popup window is attached as a children of the document root element so it will be excluded from full-screen.

In order to fix this I think we'd need to:

1. Listen for `fullscreenchange` events on the `Document`
2. Move the popup window element to be a child of `DocumentOrShadowRoot.fullscreenElement` when entering full-screen mode (and restoring it when leaving full-screen mode)

Even then I'm not entirely sure it would work. I think it would be worth trying, however, since Netflix is a pretty worthwhile usecase.

**Comment by birtles** [comment]
I went to look at this today but for me Netflix is rendering subtitles using images.

Specifically I see the following structure for the subtitle content:

![image](https://user-images.githubusercontent.com/1232595/119589280-73b49980-be0d-11eb-9031-24a50bc531af.png)

@Orzelius Has this changed for you too? Or is there some setting I need to tweak?

**Comment by Orzelius** [comment]
@birtles sorry for late reply, but I was using an extension to render subtitles as text. The problem still exists for the text displayed in the UI.
![image](https://user-images.githubusercontent.com/33936483/123507313-65a6a280-d671-11eb-9ea7-94075c4f18ab.png)

**Comment by nonetrix** [comment]
same here but on animelon seems to just not like full screen?

**Comment by birtles** [comment]
What's the name of the extension to render subtitles as text?

**Comment by birtles** [comment]
I think getting the popup to show in fullscreen should be possible but if it's not useful for reading subtitles it's probably not worth it.
