### ISSUE TITLE
The shift modifier key behaving differently from before

### ISSUE THREAD

**Issue by Orzelius** [birchill/10ten-ja-reader#650]
At some point (I'm not sure if it's a rikaichamp update or firefox) the shift modifier stopped working as before.

**Before:** I can hit `ctrl+shift` and I will see kanji definitions immediately. Then I can just more the cursor around and see kanji definitions quickly.

**Now:** I have to `ctrl` and hover, release `ctrl` and then have to press `shift` to see the kanji definition. This seems less efficient to me as I no longer can quickly see many kanji definitions as I have to repeat the abovementioned ritual.

Is this issue on my side or was it an update to firefox/rikaichamp that broke it?

**Comment by birtles** [comment]
No that's totally my fault. I didn't think anyone knew about that shortcut or was using it and it was complicating things so I dropped it in https://github.com/birchill/10ten-ja-reader/commit/d776cd0b2255ab23ca121d3ba2923ef830bfce01.

I'll add it back in the next version (and make the key more discoverable/configurable). Thanks for filing this issue and letting me know you find it useful! Sorry about the breakage.

**Comment by birtles** [comment]
@Orzelius I started to look into this, but I have a quick question. Did you disable <kbd>Shift</kbd> as a key to toggle dictionaries?

It seems to me using <kbd>Shift</kbd> to force kanji lookup conflicts with using <kbd>Shift</kbd> to toggle between dictionaries. I'm thinking of making the settings page automatically unselect <kbd>Shift</kbd> for toggling dictionaries if you enable it for forcing kanji lookup.

**Comment by Orzelius** [comment]
> Did you disable Shift as a key to toggle dictionaries?

Nope.

> I'm thinking of making the settings page automatically unselect Shift for toggling dictionaries if you enable it for forcing kanji lookup.

I think that makes sense.

> if you enable it for forcing kanji lookup.

How can I do that in settings?

**Comment by birtles** [comment]
Thanks for the very fast reply!

> > Did you disable Shift as a key to toggle dictionaries?
> 
> Nope.

Oh, that's odd. For me if I hold down shift, it cycles through the dictionaries so I could never get the kanji lookup mode to work.

> > if you enable it for forcing kanji lookup.
> 
> How can I do that in settings?

Oh, there's no setting yet. One of the reasons I got rid of the Shift behavior was because it wasn't discoverable. So now I want to add it back but make it discoverable and configurable.

**Comment by Orzelius** [comment]
> I hold down shift, it cycles through the dictionaries

It's the same for me with `enter`, it just starts to cycle the dictionaries very fast, but for some reason, with shift it just switched to the next one I guess?

**Comment by birtles** [comment]
Yeah, it's odd. I guess we could try only switching dictionaries on `keyup` for <kbd>Shift</kbd>. That might allow using <kbd>Shift</kbd> for both cycling dictionaries and for kanji lookup. It's a bit complicated though.

**Comment by birtles** [comment]
I dug into how this used to work, and it looks like it only worked if you _also_ have the "hold to show" keys setting enabled because we have the following condition that means that <kbd>Ctrl</kbd> + <kbd>Shift</kbd> would be ignored:

https://github.com/birchill/10ten-ja-reader/blob/1fe4a9488bb1cf6332c281b53b18e181fe000468/src/content.ts#L305-L316

That's not great so I've made something that should work regardless of the "hold to show" key settings.

I tried using the `keyup` approach but it was incredibly complicated so instead I just added another boolean flag to detect when we are in "force kanji lookup" mode and ignore extra <kbd>Shift</kbd> keydown events in that case.

**Comment by birtles** [comment]
I have finally released a new version containing this fix. For now you need to manually turn it on in the options.
