### ISSUE TITLE
Popup is shown when switching tabs via shortcut and mouse happens to be on Japanese text

### ISSUE THREAD

**Issue by Orzelius** [birchill/10ten-ja-reader#710]
The `ctrl+tab` and `ctrl+shift+tab` shortcuts make the popup show up when the mouse happens to be on Japanese text on the tab that is being switched to.

This doesn't bother me one bit, but maybe somebody finds it annoying.

**Comment by birtles** [comment]
> The `ctrl+tab` and `ctrl+shift+tab` shortcuts make the popup show up when the mouse happens to be on Japanese text on the tab that is being switched to.

Are you using <kbd>Ctrl</kbd> as the key to activate the popup?

We have code that tries to show the popup immediately if you press the "hold to show" keys. At the point when you press <kbd>Ctrl</kbd> we don't know if you're going to press <kbd>Tab</kbd> or not so it just shows the popup.

We recently made this _not_ show if you are in a textbox so that the text selection doesn't change:

https://github.com/birchill/10ten-ja-reader/blob/7cd657c997a192f5cd9cb918ed52a8c3c3755838/src/content.ts#L355-L368

We could make it never show until you move the mouse but I wonder if that would make the add-on feel less responsive?

Alternatively we could wait a moment before showing the popup but that would introduce a bit of complexity.

**Comment by Orzelius** [comment]
Yes, I'm using ctrl as the modifier. I think this is not much of an issue, so I'm closing this.
