### ISSUE TITLE
Text is not recognized for HyperChat

### ISSUE THREAD

**Issue by LittleVulpix** [birchill/10ten-ja-reader#758]
When using HyperChat ( https://github.com/LiveTL/HyperChat ) , the text in the chat window of Hyperchat is not picked up by 10ten reader.

I saw some reference to HyperChat here so I'm first logging the issue here, but if you think it belongs with HyperChat instead, please let me know.

Thank you.

**Comment by birtles** [comment]
Hi!

Thanks for filing this.

Unfortunately HyperChat runs in a `moz-extension://` iframe and Web Extensions simply aren't allowed to run in another extension's page. (Specifically, the Web extension content scripts are not added to pages whose protocol is an extension page. See https://stackoverflow.com/questions/10196258/does-content-scripts-matches-chrome-extension-work)

As a result, for LiveTL you need to disable HyperChat in order to see the 10ten popups.

I'm afraid there's not anything we can do here as this is a limitation of Web Extensions. If HyperChat is modified to run in a regular `https://` etc. Web page instead then 10ten should work without problem.

(Note that if you open the LiveTL window and disable HyperChat you can use 10ten in Firefox but not Chrome since Chrome won't allow other extensions to be loaded when the top-most window is an extension window. Firefox allows loading other extensions for descendant iframes if that are regular `https://` etc. pages.)

**Comment by birtles** [comment]
Closing this for now but please let me know if I've misunderstood. Sorry I couldn't help more.

**Comment by LittleVulpix** [comment]
Aha, I see. You have not misunderstood. It is a shame, because HyperChat really does resolve a lot of the issues I have with the chat, but this limitation is very inconvenient. But I understand it's a design limitation of the browser, not that of 10ten reader.

Thank you for the response!
