### ISSUE TITLE
Better handling of restrictions

### ISSUE THREAD

**Issue by nicolasmaia** [birchill/10ten-ja-reader#839]
Looking at 入苑 (https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=1465750.1), I don't think 10ten should make the alternative form 入園 visible at all, since it's never used in that sense.

**Comment by birtles** [comment]
Just to check I understand, is the idea that we would only show kanji headwords that match the looked-up text? That is, hiding the kanji headwords that are currently showed in a semi-transparent manner. Or have I misunderstood?

That seems reasonable to me. I think initially I was being conservative because I wasn't sure if it was sometimes useful to have the full set of headwords there.

For example, if a user is looking up 出逢い, perhaps it is useful to know that the definition they are seeing is actually the same as for 出会い so they can understand, "Oh, this is another form of 出会い which I already know. It possibly has a different nuance in this case, but at least as far as this dictionary is concerned, it has roughly the same meaning".

Similarly for 入苑 which JMdict marks as "iK", it's probably useful to know that 入園 is the more common way of writing it? What do you think?

**Comment by nicolasmaia** [comment]
Actually, I rethought this and I think it'd be a bad idea to remove it. I think you're right, it is useful to have it there. Sorry!

**Comment by birtles** [comment]
> Actually, I rethought this and I think it'd be a bad idea to remove it. I think you're right, it is useful to have it there. Sorry!

No problem, thanks for the suggestion and for all the thought you put into it!
