### ISSUE TITLE
Disable extension on `application/xml` pages

### ISSUE THREAD

**Issue by ian-h-chamberlain** [birchill/10ten-ja-reader#902]
In Firefox, enabling this extension causes display issues when enabled on an `application/xml` page.

Example: https://www.w3.org/2009/XMLSchema/XMLSchema.xsd

![Screen Shot 2022-02-03 at 11 16 58 AM](https://user-images.githubusercontent.com/11131775/152382825-e3ef98ec-dc6e-4aea-9ad8-f56d617537a0.png)

With the extension disabled:

![Screen Shot 2022-02-03 at 11 17 08 AM](https://user-images.githubusercontent.com/11131775/152382800-917c39c1-447c-4361-ba5c-bad6d54b3916.png)

With it enabled:

![Screen Shot 2022-02-03 at 11 17 13 AM](https://user-images.githubusercontent.com/11131775/152382859-8ed78d7f-912c-4065-b985-b70f38bc86c6.png)

I am guessing this is due to injecting some styles / JS into the page, which works fine on normal HTML but not so well on raw XML like this.

Proposed solution: Check the MIME type of a page and skip running the extension if the page is `application/xml`, or more generically – only run the extension if the page is type `text/html`.

**Comment by birtles** [comment]
Thanks for reporting this!

I can reproduce it and it certainly seems annoying. Sorry about that. I'll look into it later today.

I'm not sure the MIME type is the way to go, however, since XHTML can apparently be served as `application/xml` and we should still support that. Instead, I think we can check the `namespaceURI` of the `documentElement` and only inject elements if it's the XHTML or the SVG namespace. That should fix that particular page since its namespace is `https://www.w3.org/2001/XMLSchema`.

**Comment by ian-h-chamberlain** [comment]
Wow, thanks for the quick turnaround, awesome! Love this extension
