### ISSUE TITLE
Not functional on Bibi Reader

### ISSUE THREAD

**Issue by RawToast** [birchill/10ten-ja-reader#937]
I mentioned this in #803, but feel like it should be it's own issue.

I've played around with [Bibi reader](https://github.com/satorumurmur/bibi) and originally had issues on iOS, but it seems they are prevalent on the desktop version of Safari too. I find this viewer is potentially better than ttu as it doesn't load everything so it seems better on slower machines, Safari, etc.

I uploaded their reader here: http://opposite-10.surge.sh  just dump in any epub.

Issues: 

* I can get the 'puck' to display, but it cannot be dragged.
* No definitions on pressing the shortcut (note the text isn't even highlighted, like if you do so on nhk's site)

**Comment by birtles** [comment]
Thank you for filing this! Yes, I can reproduce this.

It looks like Bibi reader is doing a _lot_ of event capturing and blocking. e.g. it listens for the `pointermove` event on the root element in the capture phase and calls `stopPropagation` on it so that 10ten never gets a chance to see it.

![image](https://user-images.githubusercontent.com/1232595/156873114-12866ff9-a851-44f4-b1f6-d78cffb994ec.png)

This is going to take quite a bit of work to fix I think.

If I turn off enough event handlers I can get lookup to work but the positioning seems off so that will need work too:

![image](https://user-images.githubusercontent.com/1232595/156873184-ccaffefd-1644-494f-9a57-2e9e3cd66a82.png)

**Comment by birtles** [comment]
I'm not sure how soon I will be able to fix this but, for my own reference, there is a link in [this comment](https://github.com/birchill/10ten-ja-reader/issues/803#issuecomment-1059649451) to a demo book: https://imadokishimane.bex.jp/ebook/?book=imadoki_0302

**Comment by RawToast** [comment]
By the way, I believe Bibi is based on Epub.js So if you want a simple example try any of their example pages, I can't get 10 to work in those either.

Now I see why everything was done manually in TTU reader. These libraries do too much magic 😆

**Comment by birtles** [comment]
I'm not sure why but today when I tried simply registering the `pointerdown` event listener in the capture phase things seem to work. Fingers crossed that helps 🤞
