### ISSUE TITLE
Conjugation parsing interference between -たら and -らしい

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#954]
Currently (v1.9.0) 10ten prefers parsing the conjugation as the -tara form of the verb, when in reality it's the past tense plus -rashii, e.g.

治したらしい

![screenshot of 10en parsing 治したらしい](https://user-images.githubusercontent.com/28300/168465004-ace41333-45de-4f4c-8113-df09abef32d4.png)

**Comment by SaltfishAmi** [comment]
It doesn't really "prefer `-tara form of verb` **over `past tense plus -rashii`**", because it recognizes -tara as an inflected form of the verb, but not -rashii.

See https://github.com/birchill/10ten-ja-reader/blob/main/src/background/deinflect.ts : it does not contain rashii.

So the logic is simple here: 治ったら is longer than 治った, so it take the first. It's exactly the same issue as https://github.com/birchill/10ten-ja-reader/issues/641#issuecomment-869116515 .

**Comment by Tomalak** [comment]
@SaltfishAmi  You're right. I completely forgot that I already reported the exact same thing. Let's close this then.
