### ISSUE TITLE
Incorrect popup handling in flexbox elements

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#990]
On [Hikibiki](https://hikibiki.app/), this happens in 1.12.4:

![Animation](https://user-images.githubusercontent.com/28300/190016115-13df4460-8e04-4d9f-a981-a4d468e328c2.gif)

**Comment by birtles** [comment]
Thanks for filing this! That's definitely weird.

**Comment by birtles** [comment]
This appears to be an existing issue, as opposed to a recent regression.

It looks like the logic we have for re-using the last result fails to perform the distance check we use when we do a new lookup. We could just always perform that distance check, but it will likely hurt performance since we'll flush layout more often. I think we need to cache the position of the text and check that before re-using a previous result.

**Comment by Tomalak** [comment]
This seems to have been an incredibly involved fix/rewrite. Thank you!

**Comment by birtles** [comment]
Thank you! Yeah, it was three solid days of work. Hopefully it makes it possible to fix #1130 and other bugs too.
